version: "3.8"

services:


  web:
    build: .
    ports:
      - "8000:8000"

    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/Cross
    networks:
      - cross
    depends_on:
      - postgres_db
      - redis
      # - celery

  postgres_db:
    image: postgres:latest
    container_name: app_cross_db
    restart: always
    environment:
      - POSTGRES_DB=cross
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - ./data/postgres_db:/var/lib/postgresql/data  # Mounting the PostgreSQL data volume
    networks:
      - cross

  redis:
    image: redis:latest
    container_name: app_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - cross

  celery:
    build: .
    command: celery -A core worker --loglevel=info 
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/core
    depends_on:
      - redis
    networks:
      - cross


networks:
  cross:
    external: true

volumes:
  postgres_db:
    driver: local